config/routes.rb
Rails.application.routes.draw do
  resources :reminders
  devise_for :users

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  belongs_to :user

  validates_presence_of :title, :description, :month_day, :month_direction, :time

  enum month_direction: %i[start_of_month end_of_month]

  def scheduled?(reminder_time)
    reminder_time >= (scheduled_datetime - 30.minutes) && reminder_time <= scheduled_datetime
  end

  def month_schedule_day
    start_of_month? ? month_day : Time.days_in_month(Date.today.month) - month_day
  end

  private

  def scheduled_datetime
    Time.new( schedule_date.year,
              schedule_date.month,
              schedule_date.day,
              time.hour, time.min)
  end

  def schedule_date
    diff_days = (month_day - 1).days
    start_date_of_month + (start_of_month? ? diff_days : (-1 * diff_days))
  end

  def start_date_of_month
    Date.today.beginning_of_month
  end

  def end_date_of_month
    Date.today.end_of_month
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reminders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index]

  def index
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]

  def index
    @reminders = current_user.reminders
  end

  def show; end

  def new
    @reminder = current_user.reminders.new
  end

  def edit; end

  def create
    @reminder = current_user.reminders.build(reminder_params)

    respond_to do |format|
      if @reminder.save
        flash[:notice] = 'Reminder was successfully created.'
        format.html { redirect_to reminders_url }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_reminder
    @reminder = current_user.reminders.find(params[:id])
  end

  def reminder_params
    params.require(:reminder).permit(:title, :description, :month_day, :month_direction, :time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def home_controller?
    params[:cotroller].eql?('home')
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper

  def days_for_select
    Array(1..20)
  end

  def day_of_month(day)
    day.ordinalize + ' of month'
  end
end

app/views/home/index.html.erb
<div class='page-header'>
  <h2>Schedule Reminders</h2>
</div>
<div class="main-container">
  <div class="row">
    <div class="center-block">
      <h1>Hello,</h1>
      <p>Welcome to Schedule Reminders.</p>
      <p>Here you can create schedules and send reminders of the same to specified users.</p>
      <% if user_signed_in? %>
        <%= link_to 'Reminders', reminders_path, class: 'btn btn-info pull-left' %>
      <% else %>
        <%= link_to 'Signup', new_user_registration_path, class: 'btn btn-info pull-left' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert" id='flash'>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default head-bg" role="navigation">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">Schedule Reminder</a>
  </div>
  <div class="collapse navbar-collapse" id="navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Home', root_path unless home_controller? %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Login', new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedule Reminder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages' %>
    <div class="container-fluid">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/reminders/_form.html.erb
<%= form_with(model: reminder, local: true) do |form| %>
  <% if reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>
      <ul>
      <% reminder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <div class="col-md-6">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-6">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-6">
      <%= form.collection_radio_buttons :month_direction, [['start_of_month', 'Start of Month'] ,['end_of_month', 'End of month']], :first, :last , style: "display:inline", default: true %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-6">
      <%= form.label :month_day %>
      <%= form.select(:month_day, days_for_select, {}, {class: 'form-control'}) %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-6">
      <%= form.label :time %>
      <%= form.text_field :time, value: (@reminder.time.present? ? @reminder.time.strftime("%H:%M %p") : form.object.time ), class: 'form-control timepicker' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>
<br/>

app/views/reminders/edit.html.erb
<div class='page-header'>
  <h2>Editing Reminder</h2>
</div>

<div class="sub-container">
  <%= render 'form', reminder: @reminder %>
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'Show', @reminder %> |
      <%= link_to 'Back', reminders_path %>
    </div>
  </div>
</div>

app/views/reminders/index.html.erb
<div class="page-header">
  <h2>Reminders</h2>
  <%= link_to 'Create Reminder', new_reminder_path, class: 'btn btn-primary pull-right' %>
</div>

<% if @reminders.blank? %>
  <div>
    <h3> No reminder created yet!!!!</h3>
  </div>
<% else %>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Day</th>
        <th scope="col">Time</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>

    <tbody style="background-color: #eeeeee;">
      <% @reminders.each do |reminder| %>
        <tr>
          <td><%= reminder.title %></td>
          <td><%= reminder.description %></td>
          <td><%= day_of_month(reminder.month_schedule_day) %></td>
          <td><%= reminder.time.strftime("%H:%M %p") %></td>
          <td>
            <%= link_to 'View', reminder_path(reminder), class: 'btn btn-success' %>
            <%= link_to 'Edit', edit_reminder_path(reminder), class: 'btn btn-primary' %>
            <%= link_to 'Remove', reminder_path(reminder), remote: true, class: 'btn btn-danger delete_group', method: :delete, data: {confirm: 'Are you sure?'} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/reminders/new.html.erb
<div class='page-header'>
  <h2>New Reminder</h2>
</div>

<div class="sub-container">
  <%= render 'form', reminder: @reminder %>
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'Back', reminders_path %>
    </div>
  </div>
</div>

app/views/reminders/show.html.erb
<div class='page-header'>
  <h2><%= @reminder.title %></h2>
</div>

<div class="sub-container">
  <p>
    <strong>Description:</strong>
    <%= @reminder.description %>
  </p>

  <p>
    <strong>Day:</strong>
    <%= day_of_month(@reminder.month_schedule_day) %>
  </p>

  <p>
    <strong>Time:</strong>
    <%= @reminder.time.strftime("%H:%M %p") %>
  </p>

  <div class="row">
    <div class="col-md-12">
      <%= link_to 'Edit', edit_reminder_path(@reminder) %> |
      <%= link_to 'Back', reminders_path %>
    </div>
  </div>
</div>